blank_issues_enabled: false
contact_links:
  - name: Katki rehberi
    url: https://github.com/mehmetfiskindal/cvgeanetor/blob/master/CONTRIBUTING.md
    about: Issue acmadan once katki rehberini oku
